sudo: required

language: ruby

services:
  - docker

# whitelist
branches:
  only:
    - master

before_install:
  - docker build -t murphylab/matlabmcr2016b .

script:
  - docker images 
  - docker run -d murphylab/matlabmcr2016b /bin/sh -c "ls -lt"
